#!/bin/bash
set -uo pipefail

# FreePBX Transcription Module - Post-call recording upload script
# Uploads recording to transcription server via HTTP and triggers transcription.
#
# Called by FreePBX after a call recording completes.
# Usage (full path mode):   transcription-upload.sh /full/path/to/recording.wav
# Usage (component mode):   transcription-upload.sh YEAR MONTH DAY unused unused FILENAME
#
# Configuration is read from /etc/asterisk/transcription.conf (generated by the module).

CONF_FILE="/etc/asterisk/transcription.conf"
LOG_TAG="transcription-upload"
LOG_HELPER="/var/lib/asterisk/agi-bin/transcription-log.php"
MONITOR_DIR="/var/spool/asterisk/monitor"

# Log to database via helper script
log_result() {
    local filename="$1" status="$2" error="${3:-}"
    if [ -x "$LOG_HELPER" ]; then
        /usr/bin/php "$LOG_HELPER" "$filename" "$status" "$error" 2>/dev/null
    fi
}

# Load configuration
if [ ! -f "$CONF_FILE" ]; then
    logger -t "$LOG_TAG" "ERROR: Config file $CONF_FILE not found"
    exit 1
fi
source "$CONF_FILE"

# Check if enabled
if [ "$ENABLED" != "true" ]; then
    logger -t "$LOG_TAG" "Module disabled, skipping upload"
    exit 0
fi

# Determine recording file path and filename
if [ $# -eq 0 ]; then
    logger -t "$LOG_TAG" "ERROR: No arguments provided. Expected recording file path."
    exit 1
fi

RECORDING_PATH="$1"

# If path is relative (e.g. "2026/04/15/file.wav" from MIXMONITOR_FILENAME),
# prepend the Asterisk monitor directory
if [[ "$RECORDING_PATH" != /* ]]; then
    RECORDING_PATH="${MONITOR_DIR}/${RECORDING_PATH}"
fi

FILENAME=$(basename "$RECORDING_PATH")

# Validate recording file exists
if [ ! -f "$RECORDING_PATH" ]; then
    logger -t "$LOG_TAG" "ERROR: Recording file not found: $RECORDING_PATH"
    exit 1
fi

# Validate required config
if [ -z "$SERVER_HOST" ] || [ -z "$API_KEY" ]; then
    logger -t "$LOG_TAG" "ERROR: Missing required config (SERVER_HOST or API_KEY)"
    exit 1
fi

SERVER_PORT="${SERVER_PORT:-8600}"

# --- Upload file and trigger transcription in one request ---
logger -t "$LOG_TAG" "Uploading $FILENAME to http://${SERVER_HOST}:${SERVER_PORT}/upload"

RESPONSE=$(curl -s -w "\n%{http_code}" \
    -X POST \
    -H "X-API-KEY: ${API_KEY}" \
    -F "file=@${RECORDING_PATH}" \
    --connect-timeout 10 \
    --max-time 300 \
    "http://${SERVER_HOST}:${SERVER_PORT}/upload" 2>&1)

CURL_EXIT=$?

# Split response body and HTTP status code
HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ $CURL_EXIT -ne 0 ]; then
    logger -t "$LOG_TAG" "ERROR: Upload failed (curl exit code $CURL_EXIT) for $FILENAME"
    log_result "$FILENAME" "error" "curl exit code: $CURL_EXIT"
    exit 1
fi

if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
    logger -t "$LOG_TAG" "ERROR: Upload returned HTTP $HTTP_CODE for $FILENAME: $BODY"
    log_result "$FILENAME" "error" "HTTP $HTTP_CODE: $BODY"
    exit 1
fi

logger -t "$LOG_TAG" "Upload successful (HTTP $HTTP_CODE) for $FILENAME"
log_result "$FILENAME" "success" ""

exit 0
